"""
Database initialisation and schema.

Uses SQLite with WAL mode to handle concurrent reads/writes safely
(fills, position updates, and risk checks can all write simultaneously).

All schema changes must be additive — never drop or rename columns once
the schema has been deployed to a live account.
"""

import aiosqlite
import logging
from contextlib import asynccontextmanager
from pathlib import Path

logger = logging.getLogger(__name__)

DB_PATH = Path("data/trading.db")

# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

SCHEMA = """
PRAGMA journal_mode = WAL;
PRAGMA synchronous  = NORMAL;
PRAGMA foreign_keys = ON;

-- Wheel cycle tracking: the primary unit of performance for Strategy 1.
-- A cycle spans from CSP entry through assignment through CC exit.
CREATE TABLE IF NOT EXISTS wheel_cycles (
    cycle_id          TEXT PRIMARY KEY,
    underlying        TEXT NOT NULL,
    started_at        DATETIME NOT NULL,
    closed_at         DATETIME,
    total_pnl         DECIMAL(10,2),
    capital_used      DECIMAL(10,2),
    cycle_return_pct  DECIMAL(6,4),
    shares_assigned   BOOLEAN DEFAULT FALSE,
    status            TEXT DEFAULT 'open'    -- open, closed
);

-- Every trade: entry, exit, outcome, rule context.
CREATE TABLE IF NOT EXISTS trades (
    trade_id                 TEXT PRIMARY KEY,
    wheel_cycle_id           TEXT REFERENCES wheel_cycles(cycle_id),
    underlying               TEXT NOT NULL,
    strategy                 TEXT NOT NULL,  -- CSP, CoveredCall, BullPutSpread, LEAPCall
    bucket                   TEXT NOT NULL,  -- Core, Tactical, Momentum
    legs                     JSON NOT NULL,  -- [{strike, expiry, right, qty, action}]
    entry_date               DATETIME NOT NULL,
    entry_credit             DECIMAL(10,2),
    entry_ivr                DECIMAL(5,1),
    entry_delta              DECIMAL(5,3),
    entry_dte                INTEGER,
    entry_underlying_price   DECIMAL(10,2),  -- underlying spot at entry (for LEAP stop calc)
    entry_config             JSON,           -- snapshot of risk config at entry time
    -- Rule monitoring
    rule_tags                JSON,           -- ["eod_momentum", "ivr_above_40", ...]
    entry_signals            JSON,           -- {"ivr": 44, "dte": 38, "volume_ratio": 1.4}
    -- Exit
    exit_date                DATETIME,
    exit_price               DECIMAL(10,2),
    pnl                      DECIMAL(10,2),
    exit_reason              TEXT,           -- profit_target, stop_loss, expiry, roll, manual, assignment
    outcome                  TEXT,           -- Win, Loss, Scratch, Rolled, Assigned
    -- Quality flags
    was_within_delta_target  BOOLEAN,
    was_ivr_above_threshold  BOOLEAN,
    -- LEAP-specific stop/target levels (null for non-LEAP strategies)
    stop_price               DECIMAL(10,2),
    profit_target_price      DECIMAL(10,2),
    status                   TEXT DEFAULT 'open',   -- open, closed
    created_at               DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_trades_underlying ON trades(underlying);
CREATE INDEX IF NOT EXISTS idx_trades_status     ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_strategy   ON trades(strategy);

-- Live position state — Greeks and P&L updated on each tick/poll.
CREATE TABLE IF NOT EXISTS positions (
    position_id     TEXT PRIMARY KEY,
    trade_id        TEXT REFERENCES trades(trade_id),
    underlying      TEXT NOT NULL,
    current_value   DECIMAL(10,2),
    unrealised_pnl  DECIMAL(10,2),
    delta           DECIMAL(8,4),
    gamma           DECIMAL(8,4),
    theta           DECIMAL(8,4),
    vega            DECIMAL(8,4),
    dte_remaining   INTEGER,
    last_updated    DATETIME
);

-- Trade proposals: generated by scanner, pending human approval (L2).
CREATE TABLE IF NOT EXISTS proposals (
    proposal_id      TEXT PRIMARY KEY,
    underlying       TEXT NOT NULL,
    strategy         TEXT NOT NULL,
    trade_card_json  JSON NOT NULL,
    status           TEXT DEFAULT 'pending',  -- pending, approved, rejected, expired
    created_at       DATETIME DEFAULT CURRENT_TIMESTAMP,
    expires_at       DATETIME NOT NULL,       -- created_at + ttl, hard cap at 4pm ET
    actioned_at      DATETIME
);

-- Order lifecycle: from client-side UUID creation through to fill.
-- client_order_id is written to DB BEFORE the order is submitted to IBKR
-- to enable idempotent recovery on crash.
CREATE TABLE IF NOT EXISTS orders (
    client_order_id  TEXT PRIMARY KEY,   -- UUID generated before submission
    ibkr_order_id    INTEGER,
    proposal_id      TEXT REFERENCES proposals(proposal_id),
    trade_id         TEXT REFERENCES trades(trade_id),
    status           TEXT NOT NULL,      -- pending_submit, submitted, pending_fill,
                                         --   filled, cancelled, repriced, expired
    expected_price   DECIMAL(10,2),      -- mid at order creation
    fill_price       DECIMAL(10,2),      -- actual fill
    slippage         DECIMAL(10,2),      -- fill_price - expected_price
    submitted_at     DATETIME,
    filled_at        DATETIME,
    created_at       DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Risk circuit breaker events.
CREATE TABLE IF NOT EXISTS risk_events (
    event_id      TEXT PRIMARY KEY,
    event_type    TEXT NOT NULL,  -- daily_limit, weekly_limit, monthly_limit,
                                  --   strike_tested, pdt_warning, reconciliation_mismatch
    details       JSON,
    triggered_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
    resolved_at   DATETIME
);

-- IV history for IVR calculation.
-- Bootstrap: 252 days of historical IV per ticker before first scan.
-- Updated daily at 4:15pm ET.
CREATE TABLE IF NOT EXISTS iv_history (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker  TEXT    NOT NULL,
    date    DATE    NOT NULL,
    iv      DECIMAL(6,4) NOT NULL,   -- e.g. 0.42 = 42% implied volatility
    UNIQUE(ticker, date)
);
CREATE INDEX IF NOT EXISTS idx_iv_history_ticker_date ON iv_history(ticker, date);

-- Audit log: every /setconfig change is recorded here.
CREATE TABLE IF NOT EXISTS config_changes (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    param       TEXT NOT NULL,
    old_value   TEXT,
    new_value   TEXT NOT NULL,
    changed_by  TEXT NOT NULL,   -- 'user' or 'system'
    changed_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);
"""

# ---------------------------------------------------------------------------
# Initialisation
# ---------------------------------------------------------------------------

async def init_db(db_path: Path = DB_PATH) -> None:
    """
    Create database file, enable WAL mode, and run schema migrations.

    Safe to call on every startup — all CREATE TABLE statements use
    IF NOT EXISTS. Schema changes must be additive only.
    """
    db_path.parent.mkdir(parents=True, exist_ok=True)

    async with aiosqlite.connect(db_path) as db:
        await db.executescript(SCHEMA)
        await db.commit()

    logger.info("Database initialised: %s", db_path)


@asynccontextmanager
async def get_db(db_path: Path = DB_PATH):
    """
    Async context manager for a database connection with WAL mode and foreign keys.

        async with get_db() as db:
            ...
    """
    async with aiosqlite.connect(db_path) as conn:
        conn.row_factory = aiosqlite.Row
        await conn.execute("PRAGMA journal_mode = WAL")
        await conn.execute("PRAGMA foreign_keys = ON")
        yield conn
